### PR TITLE
add NOMINATIM_URL env var

### PR DESCRIPTION
**Pull request by ubergesundheit**
Allows to configure the nominatim instance to use for import.

TODO

- [x] Test with custom nominatim instance
- [x] Document

### CODE REVIEW

**Comment by ubergesundheit** [comment]
This seems to run fine (does not crash) with a `NOMINATIM_URL` in the .env. Is there a way to test geocoding with a command? `manage.py import_json` looks like it does not retry geocoding

**Comment by konstin** [comment]
Good question, I've added two manage.py commands for that: `test_geocoding` for just testing the setup and `retry_geoding` for retrying all location without coordinates (i.e. those locations that failed the last time).

**Comment by ubergesundheit** [comment]
thanks, I'll rebase against master and test

**Comment by ubergesundheit** [comment]
I ran `retry_geocoding` against my nominatim instance to test this. It works!

**Comment by konstin** [comment]
Thank you!

**Pull request merged**
